### ISSUE TITLE
Generate error when a 200 response has no content

### ISSUE THREAD

**Issue by ackushiw-flutterwave** [Elevista/nuxtswagger#1]
Hi there, thanks for this handy library. I just found a issue when generating types:

When 200 responses only have `description` I get the following error

```bash
node_modules/nuxtswagger/dist/schema/v3/Template.js:15
        const schema = (_a = content['application/json']) === null || _a === void 0 ? void 0 : _a.schema;
                                    ^

TypeError: Cannot read property 'application/json' of undefined
```
<br>

Can you add support for responses with no return value?

```json
{
  "description": "object created"
}
```

**Comment by Elevista** [comment]
Thanks for reporting the issue.
I marked content field as optional in Response.
It will be applied in the next release.

https://github.com/Elevista/nuxtswagger/blob/c44ce6ff537652b0c6f319e4bdb6ab78a04b8432/src/schema/v3/Spec.ts#L63-L66
