### ISSUE TITLE
Set options using nuxt.config baseurl not working

### ISSUE THREAD

**Issue by chsami** [Elevista/nuxtswagger#8]
The following code does not seem to set the baseurl. Anybody else has this issue?

```
 publicRuntimeConfig: {
    nuxtswagger: [
      {
        pluginName: 'api1',
        axiosConfig: { baseURL: process.env.api1},
      },
      {
        pluginName: 'api2',
        axiosConfig: { baseURL: process.env.api2},
      },
}
```

**Comment by Elevista** [comment]
![image](https://user-images.githubusercontent.com/9513647/148288109-580369e7-fae5-4a77-a64f-c9972660209c.png)
![image](https://user-images.githubusercontent.com/9513647/148288206-cc5d15d8-a858-4e5c-bf2d-0a8b3835b875.png)
![image](https://user-images.githubusercontent.com/9513647/148288213-db84d3a6-a57b-4e49-acd5-b6a1d04793d3.png)

Can't reproduce 🥲
